---

- name: ensures that server directory `{{ steamcmd_user_home }}.klei/{{ dst_shard_name }}/` exists
  file:
    path: '{{ steamcmd_user_home }}.klei/{{ dst_shard_name }}/Cluster_1/Master'
    state: directory

- name: creates server.ini file
  template:
    src: server/server.ini.j2
    dest: '{{ steamcmd_user_home }}.klei/{{ dst_shard_name }}/Cluster_1/Master/server.ini'

- name: creates cluster.ini file
  template:
    src: server/cluster.ini.j2
    dest: '{{ steamcmd_user_home }}.klei/{{ dst_shard_name }}/Cluster_1/cluster.ini'

- name: creates cluster token file
  template:
    src: server/cluster_token.txt.j2
    dest: '{{ steamcmd_user_home }}.klei/{{ dst_shard_name }}/Cluster_1/cluster_token.txt'

- name: creates world generation file.
  template:
    src: server/worldgenoverride.lua.j2
    dest: '{{ steamcmd_user_home }}.klei/{{ dst_shard_name }}/Cluster_1/Master/worldgenoverride.lua'
